# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Testing Name
title: Digital Archivist & Librarian

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: amaobiotiji
github_username: amaoti
academic_portfolio_url: https://amaoti.github.io/academic-eportfolio/


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/otiji_headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced in digital stewardship of cultural heritage collections, with a focus on scalable workflows and equitable access. Skilled in executing large-scale digital projects within complex information architectures that connect people and collections.

  [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: "Library of Congress"
        sub_title: "<i>Digital Collections Specialist</i>"
        caption: January 2024 - Present
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: right
        sub_title: "<i>Digital Collections Technician</i>"
        caption: November 2022 - January 2024
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: right
        sub_title: "<i>Digital Conversion Technician</i>"
        caption: May 2022 - November 2022
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: right
        title: "National Museum of American History"
        sub_title: "<i>Digital Assets Contractor</i>"
        caption: April 2020 - April 2022
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: right
        title: "Creekside Digital"
        sub_title: "<i>Digital Technician Supervisor</i>"
        caption: May 2018 - April 2020
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: right
        title: "National Museum of American History"
        sub_title: "<i>Collections Intern</i>"
        caption: January 2018 - May 2018
        description: | # this will include new lines to allow paragraphs
          Description of role

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Rutgers University - New Brunswick
        sub_title: Master of Information
        caption: 2023 - 2025
        description: | # this will include new lines to allow paragraphs
          <b>Concentration:</b> Technology, Information, and Management <a href="https://comminfo.rutgers.edu/graduate-programs/master-information/concentrations/technology-information-and-management">↗️</a>
          <br>
          Accredited by the American Library Association (ALA)
          <br>
          <b>Concentration Courses:</b>
          - Competitive Intelligence
          - Database Design and Management
          - Digital Curation
          - Digital Preservation
          - Government Information Resources
          - Knowledge Management in Organizations
          - Management Principles in Information Organizations
          - Metadata for Information Professionals
          - Records Management
      - layout: top-right
        title: Howard University
        sub_title: Bachelor of Arts, History
        caption: 2014 - 2018
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Areas of Concentration: United States History; African History

  - title: Awards & Honors
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification

  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project



  - title: "Professional Service <img src='images/banner.png' alt='Photo from National Book Festival 2024 showing By The People table and LOC staff talking to the public' />"
    layout: list
    content:
      - layout: right
        title: National Museum of American History
        sub_title: Museum Ambassador
        quote: Smithsonian Institution
        caption: July 2023 - Present
        description: | # this will include new lines to allow paragraphs
          Description of role

  - title: Media & Outreach
    layout: list
    content:
      - layout: left
        border: weak
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title: Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
# Footer
footer_show_references: true
# references_title: Full CV available upon request

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
